### ISSUE TITLE
use of sudo when installing a package from npm

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/oem_node-red#1]
The readme suggests installing npm packages using sudo.  I have had trouble updating packages where this has been done.

I believe the recommendation is to not use sudo with npm.  I collected some info and [wrote a short blog](https://tech.borpin.co.uk/2017/03/27/node-red-npm-sudo-and-permissions/) on it (rather than repeat it all here).

I cannot test whether this is valid for the emonpi.

**Comment by glynhudson** [comment]
I have always used sudo to install npm packages when building the emonPi image. Sudo will need to be used to update them. I've read your blog but I still can't work out why using sudo is an issue?
